import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../core/models/models.dart';
import '../../core/services/api_usage_service.dart';
import '../../core/services/nominatim_service.dart';
import '../../core/services/supabase_init.dart';
import '../../design/widgets/widgets.dart';
import '../../design/theme.dart';

// Admin data providers
final _activeSessionsProvider =
    FutureProvider.autoDispose<List<GameSession>>((ref) async {
  final service = ref.watch(supabaseServiceProvider);
  if (service == null) return [];
  final raw = await service.getActiveSessions();
  return raw.map((e) => GameSession.fromJson(e)).toList();
});

final _allSessionsProvider =
    FutureProvider.autoDispose<List<GameSession>>((ref) async {
  final service = ref.watch(supabaseServiceProvider);
  if (service == null) return [];
  final raw = await service.getAllSessions();
  return raw.map((e) => GameSession.fromJson(e)).toList();
});

final _participantCountsProvider =
    FutureProvider.autoDispose<Map<String, int>>((ref) async {
  final service = ref.watch(supabaseServiceProvider);
  if (service == null) return {};
  final counts = await service.getSessionParticipantCounts();
  return {for (final c in counts) c['session_id'] as String: c['count'] as int};
});

final _featureRequestsProvider =
    FutureProvider.autoDispose<List<FeatureRequest>>((ref) async {
  final service = ref.watch(supabaseServiceProvider);
  if (service == null) return [];
  return service.getFeatureRequests();
});

final _gameAreasProvider =
    FutureProvider.autoDispose<List<GameArea>>((ref) async {
  final service = ref.watch(supabaseServiceProvider);
  if (service == null) return [];
  return service.getGameAreas();
});

final _recentEventsProvider =
    FutureProvider.autoDispose<List<GameEvent>>((ref) async {
  final client = ref.watch(supabaseClientProvider);
  if (client == null) return [];
  final response = await client
      .from('game_events')
      .select()
      .order('created_at', ascending: false)
      .limit(100);
  return (response as List).map((e) => GameEvent.fromJson({
    'id': e['id'],
    'sessionId': e['session_id'],
    'roundId': e['round_id'],
    'eventType': e['event_type'],
    'payload': e['payload'] ?? {},
    'createdAt': e['created_at'],
  })).toList();
});

class AdminScreen extends ConsumerStatefulWidget {
  const AdminScreen({super.key});

  @override
  ConsumerState<AdminScreen> createState() => _AdminScreenState();
}

class _AdminScreenState extends ConsumerState<AdminScreen> {
  bool _isCreating = false;
  String? _createdRoomCode;
  String? _selectedAreaId;
  final _locationController = TextEditingController();

  @override
  void dispose() {
    _locationController.dispose();
    super.dispose();
  }

  Future<void> _quickCreate(String query) async {
    final service = ref.read(supabaseServiceProvider);
    if (service == null) return;

    setState(() {
      _isCreating = true;
      _createdRoomCode = null;
    });

    try {
      // 1. Search Nominatim
      final nominatim = NominatimService();
      final places = await nominatim.search(query, limit: 1);
      nominatim.dispose();

      if (places.isEmpty || places.first.boundaryPolygon == null) {
        throw Exception('No boundary found for "$query". Try a more specific place name.');
      }

      final place = places.first;
      final polygon = place.toPolygonData();
      if (polygon == null) throw Exception('Could not parse boundary polygon');

      // 2. Create game area
      final area = GameArea(
        id: '', // will be generated by Supabase
        name: place.displayName.split(',').first,
        inclusionPolygons: [polygon],
        exclusionPolygons: [],
        centerLat: place.lat,
        centerLng: place.lng,
        defaultZoom: 13.0,
        createdBy: 'admin',
      );
      final savedArea = await service.createGameArea(area);

      // 3. Create session
      final session = await service.createSession(
        gameAreaId: savedArea.id,
        hidingPeriodSeconds: 3600,
        zoneRadiusMeters: 804.672,
        createdBy: 'admin',
      );

      setState(() {
        _createdRoomCode = session.roomCode;
        _isCreating = false;
      });
      _refresh();
    } catch (e) {
      setState(() => _isCreating = false);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(e.toString())),
        );
      }
    }
  }

  void _refresh() {
    ref.invalidate(_activeSessionsProvider);
    ref.invalidate(_allSessionsProvider);
    ref.invalidate(_participantCountsProvider);
    ref.invalidate(_featureRequestsProvider);
    ref.invalidate(_gameAreasProvider);
    ref.invalidate(_recentEventsProvider);
    ref.invalidate(apiUsageStatsProvider);
  }

  Future<void> _stopSession(String sessionId) async {
    final service = ref.read(supabaseServiceProvider);
    if (service == null) return;
    try {
      await service.stopSession(sessionId);
      _refresh();
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Session stopped')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to stop session: $e')),
        );
      }
    }
  }

  Future<void> _createGame(String areaId) async {
    final service = ref.read(supabaseServiceProvider);
    if (service == null) return;
    setState(() => _isCreating = true);
    try {
      final session = await service.createSession(
        gameAreaId: areaId,
        hidingPeriodSeconds: 3600,
        zoneRadiusMeters: 804.672,
        createdBy: 'admin',
      );
      setState(() {
        _createdRoomCode = session.roomCode;
        _isCreating = false;
      });
      _refresh();
    } catch (e) {
      setState(() => _isCreating = false);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to create game: $e')),
        );
      }
    }
  }

  Future<void> _updateFeatureStatus(String id, String status) async {
    final service = ref.read(supabaseServiceProvider);
    if (service == null) return;
    try {
      await service.updateFeatureRequestStatus(id, status);
      ref.invalidate(_featureRequestsProvider);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to update status: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final activeSessions = ref.watch(_activeSessionsProvider);
    final allSessions = ref.watch(_allSessionsProvider);
    final counts = ref.watch(_participantCountsProvider);
    final featureRequests = ref.watch(_featureRequestsProvider);
    final gameAreas = ref.watch(_gameAreasProvider);

    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => context.go('/'),
        ),
        title: const Text('Jet Lag Admin'),
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh),
            onPressed: _refresh,
          ),
        ],
      ),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          // ======= Active Games =======
          _SectionHeader(title: 'Active Games', icon: Icons.play_circle_outline),
          const SizedBox(height: 12),
          activeSessions.when(
            loading: () => const _LoadingWidget(),
            error: (e, _) => _ErrorWidget(error: e.toString()),
            data: (sessions) {
              if (sessions.isEmpty) {
                return _EmptyWidget(message: 'No active games');
              }
              return Column(
                children: sessions.map((s) {
                  final playerCount = counts.maybeWhen(
                    data: (c) => c[s.id] ?? 0,
                    orElse: () => 0,
                  );
                  return Padding(
                    padding: const EdgeInsets.only(bottom: 12),
                    child: _SessionCard(
                      session: s,
                      participantCount: playerCount,
                      onSpectate: () => context.go('/game/${s.id}/spectator'),
                      onStop: () => _stopSession(s.id),
                    ),
                  );
                }).toList(),
              );
            },
          ),

          const SizedBox(height: 28),

          // ======= Create Game =======
          _SectionHeader(title: 'Create Game', icon: Icons.add_circle_outline),
          const SizedBox(height: 12),
          JetlagCard(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Quick create from location name
                Row(
                  children: [
                    Expanded(
                      child: TextField(
                        controller: _locationController,
                        decoration: const InputDecoration(
                          hintText: 'Type a location (e.g., Midtown Manhattan)',
                        ),
                        onSubmitted: (v) {
                          if (v.trim().isNotEmpty && !_isCreating) {
                            _quickCreate(v.trim());
                          }
                        },
                      ),
                    ),
                    const SizedBox(width: 12),
                    JetlagButton(
                      label: 'Create Game',
                      icon: Icons.bolt,
                      isLoading: _isCreating,
                      onPressed: _isCreating ? null : () {
                        final q = _locationController.text.trim();
                        if (q.isNotEmpty) _quickCreate(q);
                      },
                    ),
                  ],
                ),

                const SizedBox(height: 16),
                Center(
                  child: Text(
                    '\u2014 or \u2014',
                    style: TextStyle(color: context.textSecondary, fontSize: 13),
                  ),
                ),
                const SizedBox(height: 16),

                // Draw New Area button
                Center(
                  child: JetlagButton(
                    label: 'New Game Area + Game',
                    icon: Icons.map_outlined,
                    variant: JetlagButtonVariant.primary,
                    onPressed: () => context.push('/create-game'),
                  ),
                ),

                // If areas exist, also show quick create
                gameAreas.when(
                  loading: () => const SizedBox.shrink(),
                  error: (_, __) => const SizedBox.shrink(),
                  data: (areas) {
                    if (areas.isEmpty) {
                      return Padding(
                        padding: const EdgeInsets.only(top: 12),
                        child: Text(
                          'Draw a game area on the map to get started',
                          style: TextStyle(color: context.textSecondary, fontSize: 13),
                          textAlign: TextAlign.center,
                        ),
                      );
                    }
                    return Column(
                      children: [
                        const SizedBox(height: 16),
                        Divider(color: context.border),
                        const SizedBox(height: 16),
                        Text(
                          'Or use an existing area:',
                          style: TextStyle(color: context.textSecondary, fontSize: 13),
                        ),
                        const SizedBox(height: 12),
                        DropdownButtonFormField<String>(
                          value: _selectedAreaId ?? areas.first.id,
                          decoration: const InputDecoration(labelText: 'Game Area'),
                          items: areas.map((a) => DropdownMenuItem(
                            value: a.id,
                            child: Text(a.name),
                          )).toList(),
                          onChanged: (v) => setState(() => _selectedAreaId = v),
                        ),
                        const SizedBox(height: 12),
                        Center(
                          child: JetlagButton(
                            label: 'Create Game',
                            icon: Icons.add,
                            isLoading: _isCreating,
                            onPressed: _isCreating ? null : () {
                              final areaId = _selectedAreaId ?? areas.first.id;
                              _createGame(areaId);
                            },
                          ),
                        ),
                      ],
                    );
                  },
                ),

                // Show created game link
                if (_createdRoomCode != null) ...[
                  const SizedBox(height: 16),
                  JetlagCard(
                    borderColor: context.green,
                    child: Row(
                      children: [
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text('Game Created!',
                                style: Theme.of(context).textTheme.titleMedium?.copyWith(color: context.green)),
                              const SizedBox(height: 4),
                              SelectableText('jetlag.ratz.fyi/g/$_createdRoomCode',
                                style: Theme.of(context).textTheme.bodyLarge),
                            ],
                          ),
                        ),
                        IconButton(
                          icon: const Icon(Icons.copy, size: 18),
                          onPressed: () {
                            Clipboard.setData(ClipboardData(text: 'https://jetlag.ratz.fyi/g/$_createdRoomCode'));
                            ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(content: Text('Link copied')),
                            );
                          },
                        ),
                      ],
                    ),
                  ),
                ],
              ],
            ),
          ),

          const SizedBox(height: 28),

          // ======= API Usage =======
          _SectionHeader(title: 'API Usage', icon: Icons.data_usage),
          const SizedBox(height: 12),
          _ApiUsageWidget(),

          const SizedBox(height: 28),

          // ======= Event Log =======
          _SectionHeader(title: 'Event Log', icon: Icons.list_alt),
          const SizedBox(height: 12),
          _EventLogSection(),

          const SizedBox(height: 28),

          // ======= Feature Requests =======
          _SectionHeader(title: 'Feature Requests', icon: Icons.lightbulb_outline),
          const SizedBox(height: 12),
          featureRequests.when(
            loading: () => const _LoadingWidget(),
            error: (e, _) => _ErrorWidget(error: e.toString()),
            data: (requests) {
              if (requests.isEmpty) {
                return _EmptyWidget(message: 'No feature requests');
              }
              return Column(
                children: requests.map((r) {
                  return Padding(
                    padding: const EdgeInsets.only(bottom: 12),
                    child: _FeatureRequestAdminCard(
                      request: r,
                      onStatusChange: (status) =>
                          _updateFeatureStatus(r.id, status),
                    ),
                  );
                }).toList(),
              );
            },
          ),

          const SizedBox(height: 28),

          // ======= Previous Games =======
          _SectionHeader(title: 'Previous Games', icon: Icons.history),
          const SizedBox(height: 12),
          allSessions.when(
            loading: () => const _LoadingWidget(),
            error: (e, _) => _ErrorWidget(error: e.toString()),
            data: (sessions) {
              final ended = sessions
                  .where((s) => s.status == SessionStatus.ended)
                  .toList();
              if (ended.isEmpty) {
                return _EmptyWidget(message: 'No previous games');
              }
              return Column(
                children: ended.map((s) {
                  final playerCount = counts.maybeWhen(
                    data: (c) => c[s.id] ?? 0,
                    orElse: () => 0,
                  );
                  return Padding(
                    padding: const EdgeInsets.only(bottom: 12),
                    child: _EndedSessionCard(
                      session: s,
                      participantCount: playerCount,
                    ),
                  );
                }).toList(),
              );
            },
          ),

          const SizedBox(height: 32),
        ],
      ),
    );
  }
}

// ============ Helper Widgets ============

class _SectionHeader extends StatelessWidget {
  final String title;
  final IconData icon;

  const _SectionHeader({required this.title, required this.icon});

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Icon(icon, size: 20, color: context.accent),
        const SizedBox(width: 8),
        Text(title, style: Theme.of(context).textTheme.headlineMedium),
      ],
    );
  }
}

class _LoadingWidget extends StatelessWidget {
  const _LoadingWidget();

  @override
  Widget build(BuildContext context) {
    return const Center(
      child: Padding(
        padding: EdgeInsets.all(24),
        child: CircularProgressIndicator(),
      ),
    );
  }
}

class _ErrorWidget extends StatelessWidget {
  final String error;
  const _ErrorWidget({required this.error});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Text('Error: $error', style: TextStyle(color: context.red)),
      ),
    );
  }
}

class _EmptyWidget extends StatelessWidget {
  final String message;
  const _EmptyWidget({required this.message});

  @override
  Widget build(BuildContext context) {
    return JetlagCard(
      child: Center(
        child: Text(message, style: Theme.of(context).textTheme.bodyLarge),
      ),
    );
  }
}

class _SessionCard extends StatelessWidget {
  final GameSession session;
  final int participantCount;
  final VoidCallback onSpectate;
  final VoidCallback onStop;

  const _SessionCard({
    required this.session,
    required this.participantCount,
    required this.onSpectate,
    required this.onStop,
  });

  JetlagBadgeColor _statusColor(SessionStatus status) {
    switch (status) {
      case SessionStatus.waiting:
        return JetlagBadgeColor.blue;
      case SessionStatus.hiding:
        return JetlagBadgeColor.orange;
      case SessionStatus.seeking:
        return JetlagBadgeColor.red;
      case SessionStatus.paused:
        return JetlagBadgeColor.purple;
      case SessionStatus.ended:
        return JetlagBadgeColor.green;
    }
  }

  @override
  Widget build(BuildContext context) {
    return JetlagCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Expanded(
                child: SelectableText(
                  session.roomCode,
                  style: Theme.of(context).textTheme.titleLarge?.copyWith(
                        fontFamily: 'monospace',
                        letterSpacing: 0.5,
                      ),
                ),
              ),
              JetlagBadge(
                label: session.status.name,
                color: _statusColor(session.status),
                showPulse: session.status != SessionStatus.ended &&
                    session.status != SessionStatus.waiting,
              ),
            ],
          ),
          const SizedBox(height: 8),
          Text(
            '$participantCount players  \u2022  ${_relativeTime(session.createdAt)}',
            style: Theme.of(context).textTheme.bodySmall,
          ),
          const SizedBox(height: 12),
          Row(
            children: [
              JetlagButton(
                label: 'Spectate',
                icon: Icons.visibility,
                variant: JetlagButtonVariant.secondary,
                onPressed: onSpectate,
              ),
              const SizedBox(width: 8),
              JetlagButton(
                label: 'Stop',
                icon: Icons.stop,
                variant: JetlagButtonVariant.danger,
                onPressed: onStop,
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _EndedSessionCard extends StatelessWidget {
  final GameSession session;
  final int participantCount;

  const _EndedSessionCard({
    required this.session,
    required this.participantCount,
  });

  @override
  Widget build(BuildContext context) {
    return JetlagCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Expanded(
                child: Text(
                  session.roomCode,
                  style: Theme.of(context).textTheme.titleMedium?.copyWith(
                        fontFamily: 'monospace',
                        letterSpacing: 0.5,
                      ),
                ),
              ),
              JetlagBadge(
                label: 'Ended',
                color: JetlagBadgeColor.green,
              ),
            ],
          ),
          const SizedBox(height: 6),
          Text(
            [
              '$participantCount players',
              if (session.winningTeamId != null) 'Winner: ${session.winningTeamId}',
              if (session.endedAt != null) 'Ended ${_relativeTime(session.endedAt!)}',
            ].join('  \u2022  '),
            style: Theme.of(context).textTheme.bodySmall,
          ),
          const SizedBox(height: 10),
          Row(
            children: [
              JetlagButton(
                label: 'Stats',
                icon: Icons.analytics_outlined,
                variant: JetlagButtonVariant.secondary,
                onPressed: () => context.push('/game/${session.id}/summary'),
              ),
              const SizedBox(width: 8),
              JetlagButton(
                label: 'Replay',
                icon: Icons.replay,
                variant: JetlagButtonVariant.secondary,
                onPressed: () => context.push('/game/${session.id}/replay'),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _FeatureRequestAdminCard extends StatelessWidget {
  final FeatureRequest request;
  final void Function(String status) onStatusChange;

  const _FeatureRequestAdminCard({
    required this.request,
    required this.onStatusChange,
  });

  JetlagBadgeColor _badgeColor(FeatureRequestStatus status) {
    switch (status) {
      case FeatureRequestStatus.open:
        return JetlagBadgeColor.blue;
      case FeatureRequestStatus.inProgress:
        return JetlagBadgeColor.orange;
      case FeatureRequestStatus.done:
        return JetlagBadgeColor.green;
    }
  }

  String _statusLabel(FeatureRequestStatus status) {
    switch (status) {
      case FeatureRequestStatus.open:
        return 'Open';
      case FeatureRequestStatus.inProgress:
        return 'In Progress';
      case FeatureRequestStatus.done:
        return 'Done';
    }
  }

  @override
  Widget build(BuildContext context) {
    return JetlagCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Expanded(
                child: Text(
                  request.title,
                  style: Theme.of(context).textTheme.titleLarge,
                ),
              ),
              const SizedBox(width: 8),
              JetlagBadge(
                label: _statusLabel(request.status),
                color: _badgeColor(request.status),
              ),
            ],
          ),
          if (request.description != null &&
              request.description!.isNotEmpty) ...[
            const SizedBox(height: 8),
            Text(
              request.description!,
              style: Theme.of(context).textTheme.bodyLarge,
            ),
          ],
          const SizedBox(height: 8),
          Text(
            [
              if (request.submitterName != null) request.submitterName!,
              _relativeTime(request.createdAt ?? DateTime.now()),
            ].where((s) => s.isNotEmpty).join(' \u2022 '),
            style: Theme.of(context).textTheme.bodySmall,
          ),
          const SizedBox(height: 12),
          Wrap(
            spacing: 8,
            runSpacing: 8,
            children: [
              if (request.status != FeatureRequestStatus.open)
                JetlagButton(
                  label: 'Open',
                  variant: JetlagButtonVariant.secondary,
                  onPressed: () => onStatusChange('open'),
                ),
              if (request.status != FeatureRequestStatus.inProgress)
                JetlagButton(
                  label: 'In Progress',
                  variant: JetlagButtonVariant.secondary,
                  icon: Icons.pending,
                  onPressed: () => onStatusChange('in_progress'),
                ),
              if (request.status != FeatureRequestStatus.done)
                JetlagButton(
                  label: 'Done',
                  variant: JetlagButtonVariant.primary,
                  icon: Icons.check,
                  onPressed: () => onStatusChange('done'),
                ),
            ],
          ),
        ],
      ),
    );
  }
}

class _EventLogSection extends ConsumerStatefulWidget {
  @override
  ConsumerState<_EventLogSection> createState() => _EventLogSectionState();
}

class _EventLogSectionState extends ConsumerState<_EventLogSection> {
  String? _filterType;

  static const _eventTypes = [
    null, // all
    'phase_change',
    'question_asked',
    'question_answered',
    'card_drawn',
    'card_played',
    'curse_activated',
    'round_started',
    'round_ended',
    'game_ended',
    'timer_pause',
    'timer_resume',
    'player_joined',
  ];

  @override
  Widget build(BuildContext context) {
    final eventsAsync = ref.watch(_recentEventsProvider);

    return eventsAsync.when(
      loading: () => const _LoadingWidget(),
      error: (e, _) => _ErrorWidget(error: e.toString()),
      data: (events) {
        final filtered = _filterType == null
            ? events
            : events.where((e) => e.eventType == _filterType).toList();

        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Filter chips
            SizedBox(
              height: 34,
              child: ListView(
                scrollDirection: Axis.horizontal,
                children: _eventTypes.map((type) {
                  final isSelected = _filterType == type;
                  final label = type == null
                      ? 'All'
                      : type.replaceAll('_', ' ');
                  return Padding(
                    padding: const EdgeInsets.only(right: 6),
                    child: GestureDetector(
                      onTap: () => setState(() => _filterType = type),
                      child: Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 12, vertical: 6),
                        decoration: BoxDecoration(
                          color: isSelected
                              ? context.accent.withValues(alpha: 0.15)
                              : context.surface,
                          borderRadius: BorderRadius.circular(16),
                          border: Border.all(
                            color: isSelected
                                ? context.accent
                                : context.borderSubtle,
                          ),
                        ),
                        child: Text(
                          _capitalize(label),
                          style: TextStyle(
                            fontSize: 11,
                            fontWeight:
                                isSelected ? FontWeight.w600 : FontWeight.w400,
                            color: isSelected
                                ? context.accent
                                : context.textSecondary,
                          ),
                        ),
                      ),
                    ),
                  );
                }).toList(),
              ),
            ),
            const SizedBox(height: 12),

            if (filtered.isEmpty)
              _EmptyWidget(message: 'No events')
            else
              JetlagCard(
                padding: const EdgeInsets.symmetric(vertical: 8),
                child: Column(
                  children: filtered.take(30).map((event) {
                    return Padding(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 14, vertical: 4),
                      child: Row(
                        children: [
                          Container(
                            width: 7,
                            height: 7,
                            decoration: BoxDecoration(
                              shape: BoxShape.circle,
                              color: _eventColor(event.eventType, context),
                            ),
                          ),
                          const SizedBox(width: 8),
                          Expanded(
                            child: Text(
                              _eventLabel(event),
                              style: TextStyle(
                                fontSize: 12,
                                color: context.textSecondary,
                              ),
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                          const SizedBox(width: 8),
                          if (event.createdAt != null)
                            Text(
                              _formatEventTime(event.createdAt!),
                              style: TextStyle(
                                fontSize: 10,
                                color: context.textTertiary,
                                fontFeatures: const [
                                  FontFeature.tabularFigures()
                                ],
                              ),
                            ),
                        ],
                      ),
                    );
                  }).toList(),
                ),
              ),
          ],
        );
      },
    );
  }

  Color _eventColor(String type, BuildContext context) {
    switch (type) {
      case 'phase_change':
        return context.accent;
      case 'question_asked':
        return context.orange;
      case 'question_answered':
        return context.green;
      case 'card_drawn':
      case 'card_played':
        return context.purple;
      case 'curse_activated':
        return context.red;
      case 'round_started':
      case 'round_ended':
      case 'game_started':
      case 'game_ended':
        return context.accent;
      case 'timer_pause':
      case 'timer_resume':
        return context.orange;
      case 'player_joined':
      case 'player_left':
        return context.green;
      default:
        return context.textTertiary;
    }
  }

  String _eventLabel(GameEvent event) {
    final sessionShort = event.sessionId.substring(0, 8);
    switch (event.eventType) {
      case 'phase_change':
        return '[$sessionShort] Phase \u2192 ${_capitalize(event.payload['phase'] as String? ?? '')}';
      case 'question_asked':
        return '[$sessionShort] Question (${_capitalize(event.payload['category'] as String? ?? '')})';
      case 'question_answered':
        return '[$sessionShort] Answered: ${event.payload['answerText'] ?? ''}';
      case 'card_drawn':
        return '[$sessionShort] Drew card: ${event.payload['cardId'] ?? ''}';
      case 'card_played':
        return '[$sessionShort] Played card: ${event.payload['cardId'] ?? ''}';
      case 'curse_activated':
        return '[$sessionShort] Curse: ${_capitalize(event.payload['curseType'] as String? ?? '')}';
      case 'round_started':
        return '[$sessionShort] Round ${event.payload['roundNumber'] ?? ''} started';
      case 'round_ended':
        return '[$sessionShort] Round ended';
      case 'game_ended':
        return '[$sessionShort] Game over';
      case 'timer_pause':
        return '[$sessionShort] Paused';
      case 'timer_resume':
        return '[$sessionShort] Resumed';
      case 'player_joined':
        return '[$sessionShort] Player joined team';
      default:
        return '[$sessionShort] ${_capitalize(event.eventType.replaceAll('_', ' '))}';
    }
  }

  String _formatEventTime(DateTime dt) {
    final now = DateTime.now();
    final diff = now.difference(dt);
    if (diff.inDays > 0) return '${diff.inDays}d ago';
    if (diff.inHours > 0) return '${diff.inHours}h ago';
    if (diff.inMinutes > 0) return '${diff.inMinutes}m ago';
    return 'now';
  }

  String _capitalize(String s) {
    if (s.isEmpty) return s;
    return s[0].toUpperCase() + s.substring(1);
  }
}

class _ApiUsageWidget extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final statsAsync = ref.watch(apiUsageStatsProvider);

    return statsAsync.when(
      loading: () => const _LoadingWidget(),
      error: (e, _) => _ErrorWidget(error: e.toString()),
      data: (stats) {
        if (stats == null) {
          return _EmptyWidget(message: 'API tracking not available');
        }

        return JetlagCard(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Progress bar
              Row(
                children: [
                  Expanded(
                    child: Text(
                      'This Month',
                      style: TextStyle(
                        fontSize: 14,
                        fontWeight: FontWeight.w600,
                        color: context.textPrimary,
                      ),
                    ),
                  ),
                  Text(
                    '${stats.totalCostFormatted} / ${stats.freeTierFormatted}',
                    style: TextStyle(
                      fontSize: 13,
                      fontWeight: FontWeight.w500,
                      color: context.textSecondary,
                      fontFeatures: const [FontFeature.tabularFigures()],
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 10),
              ClipRRect(
                borderRadius: BorderRadius.circular(4),
                child: LinearProgressIndicator(
                  value: stats.usagePercent,
                  minHeight: 8,
                  backgroundColor: context.surface2,
                  valueColor: AlwaysStoppedAnimation(
                    stats.usagePercent > 0.8 ? context.red : context.accent,
                  ),
                ),
              ),
              const SizedBox(height: 14),

              // Projection
              Row(
                children: [
                  Icon(Icons.trending_up, size: 14, color: context.textTertiary),
                  const SizedBox(width: 6),
                  Text(
                    'Projected: ${stats.projectedCostFormatted}/mo',
                    style: TextStyle(
                      fontSize: 12,
                      color: context.textSecondary,
                    ),
                  ),
                  const Spacer(),
                  Text(
                    '${stats.totalCalls} total calls',
                    style: TextStyle(
                      fontSize: 12,
                      color: context.textTertiary,
                    ),
                  ),
                ],
              ),

              if (stats.byType.isNotEmpty) ...[
                const SizedBox(height: 14),
                Divider(color: context.borderSubtle),
                const SizedBox(height: 10),
                ...stats.byType.map((t) => Padding(
                      padding: const EdgeInsets.only(bottom: 6),
                      child: Row(
                        children: [
                          Text(
                            t.displayName,
                            style: TextStyle(
                              fontSize: 12,
                              color: context.textSecondary,
                            ),
                          ),
                          const Spacer(),
                          Text(
                            '${t.count}x',
                            style: TextStyle(
                              fontSize: 12,
                              color: context.textTertiary,
                              fontFeatures: const [FontFeature.tabularFigures()],
                            ),
                          ),
                          const SizedBox(width: 12),
                          SizedBox(
                            width: 60,
                            child: Text(
                              t.costFormatted,
                              style: TextStyle(
                                fontSize: 12,
                                fontWeight: FontWeight.w500,
                                color: context.textPrimary,
                                fontFeatures: const [FontFeature.tabularFigures()],
                              ),
                              textAlign: TextAlign.right,
                            ),
                          ),
                        ],
                      ),
                    )),
              ],
            ],
          ),
        );
      },
    );
  }
}

String _relativeTime(DateTime dateTime) {
  final diff = DateTime.now().difference(dateTime);
  if (diff.inDays > 365) return '${diff.inDays ~/ 365}y ago';
  if (diff.inDays > 30) return '${diff.inDays ~/ 30}mo ago';
  if (diff.inDays > 0) return '${diff.inDays}d ago';
  if (diff.inHours > 0) return '${diff.inHours}h ago';
  if (diff.inMinutes > 0) return '${diff.inMinutes}m ago';
  return 'just now';
}
