services:
  web:
    image: nginx:alpine
    ports:
      - "8900:80"
    volumes:
      - ../build/web:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
